### ISSUE TITLE
Nice Job.

### ISSUE THREAD

**Issue by ids444** [pendor/SV01-BIQU-H2#1]
Looks like the original (https://www.thingiverse.com/thing:4762042) is 404 now.

I'm trying to mount the H2 on an Anycubic Chiron and like you I didn't like any I found.

Going to yry and adapt yours to the Chiron. Wish me luck.

**Comment by pendor** [comment]
Thank you!  Good luck with the remix. 

It's unfortunate the original is missing.  Considering it's licensed under CC, I don't see any problem mirroring from my original download here. I dunno if the Fusion 360 source will help you any, but it's there just in case.
